
export const LOGIN_SUCCESS = 'LOGIN_USER';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_SUCCESS = 'LOGOUT_USER';

//Current USER
export const CURRENT_USER_SIGN_OUT = 'CURRENT_USER_SIGN_OUT';
export const CURRENT_USER_SIGN_OUT_REJECTED = 'CURRENT_USER_SIGN_OUT_REJECTED';

